#!/usr/bin/env python3
"""Convert the two Business Tracker CSV exports into js/seed-data.js.

Run again any time you re-export the sheets to refresh the bundled starter data:
    python tools/parse_csv.py

It reads the CSVs from the user's Downloads folder by default; pass paths to override.
"""
import csv
import json
import os
import re
import sys
from datetime import datetime

DEFAULT_SALES = os.path.expanduser("~/Downloads/Business_Tracker_v2 - Sales.csv")
DEFAULT_EXPENSES = os.path.expanduser("~/Downloads/Business_Tracker_v2 - \U0001F4B8 Expenses.csv")

KNOWN_PLATFORMS = {"ebay": "eBay", "vinted": "Vinted", "bootsale": "Bootsale", "etsy": "Etsy"}
KNOWN_STATUS = {"delivered": "Delivered", "dispatched": "Dispatched",
                "packed": "Packed", "cancelled": "Cancelled"}
KNOWN_CATEGORIES = {"equipment", "filament", "packaging", "accessories",
                    "tools", "software", "wages", "other"}


def parse_money(raw):
    """'£1,234.56' / '-£6.00' / '' -> float. Returns 0.0 when blank/unparseable."""
    if raw is None:
        return 0.0
    s = raw.strip().replace("£", "").replace(",", "").replace('"', "")
    if s in ("", "nan", "N/A", "-"):
        return 0.0
    neg = s.startswith("-")
    s = s.lstrip("-+")
    try:
        v = float(s)
    except ValueError:
        return 0.0
    return -v if neg else v


def parse_date(raw):
    """DD/MM/YYYY -> ISO YYYY-MM-DD. Returns None if not a date."""
    raw = (raw or "").strip()
    if not re.match(r"^\d{2}/\d{2}/\d{4}$", raw):
        return None
    try:
        return datetime.strptime(raw, "%d/%m/%Y").strftime("%Y-%m-%d")
    except ValueError:
        return None


def clean_str(raw):
    s = (raw or "").strip().strip('"')
    return "" if s.lower() == "nan" else s


def parse_sales(path):
    rows = []
    with open(path, newline="", encoding="utf-8") as f:
        reader = csv.reader(f)
        for cols in reader:
            if len(cols) < 6:
                continue
            iso = parse_date(cols[0])
            if not iso:
                continue
            item = clean_str(cols[1])
            if not item:
                continue
            platform_raw = clean_str(cols[5]).lower()
            platform = KNOWN_PLATFORMS.get(platform_raw, "Other")
            status_raw = clean_str(cols[6]).lower() if len(cols) > 6 else ""
            status = KNOWN_STATUS.get(status_raw, "Delivered")
            printed_raw = clean_str(cols[7]).lower() if len(cols) > 7 else ""
            printed = "printed" in printed_raw
            revenue = parse_money(cols[2])
            landing = parse_money(cols[3])
            rows.append({
                "date": iso,
                "item": item,
                "revenue": round(revenue, 2),
                "landingCost": round(landing, 2),
                "platform": platform,
                "status": status,
                "printed": printed,
            })
    return rows


def parse_expenses(path):
    rows = []
    with open(path, newline="", encoding="utf-8") as f:
        reader = csv.reader(f)
        for cols in reader:
            if len(cols) < 4:
                continue
            iso = parse_date(cols[0])
            if not iso:
                continue
            desc = clean_str(cols[1])
            if not desc:
                continue
            amount = parse_money(cols[2])
            category = clean_str(cols[3]) or "Other"
            if category.lower() not in KNOWN_CATEGORIES:
                category = "Other"
            else:
                # normalise capitalisation to the canonical label
                category = category[0].upper() + category[1:].lower()
            rows.append({
                "date": iso,
                "description": desc,
                "amount": round(amount, 2),
                "category": category,
            })
    return rows


def main():
    sales_path = sys.argv[1] if len(sys.argv) > 1 else DEFAULT_SALES
    expenses_path = sys.argv[2] if len(sys.argv) > 2 else DEFAULT_EXPENSES

    sales = parse_sales(sales_path)
    expenses = parse_expenses(expenses_path)

    # Attach deterministic ids so re-importing never creates duplicates.
    for i, s in enumerate(sales, 1):
        s["id"] = f"seed-s-{i:04d}"
    for i, e in enumerate(expenses, 1):
        e["id"] = f"seed-e-{i:04d}"

    out_dir = os.path.join(os.path.dirname(__file__), "..", "js")
    out_path = os.path.normpath(os.path.join(out_dir, "seed-data.js"))

    rev = round(sum(s["revenue"] for s in sales), 2)
    landing = round(sum(s["landingCost"] for s in sales), 2)
    exp_total = round(sum(e["amount"] for e in expenses), 2)
    filament = round(sum(e["amount"] for e in expenses if e["category"] == "Filament"), 2)

    header = (
        "// AUTO-GENERATED by tools/parse_csv.py from the Business Tracker CSV exports.\n"
        "// Do not edit by hand — re-run the parser to refresh.\n"
        f"// Sales rows: {len(sales)} | Expense rows: {len(expenses)}\n"
        f"// Revenue £{rev:,.2f} | Landing £{landing:,.2f} | "
        f"Expenses £{exp_total:,.2f} (Filament £{filament:,.2f})\n\n"
    )
    body = (
        "export const SEED_SALES = " + json.dumps(sales, indent=2, ensure_ascii=False) + ";\n\n"
        "export const SEED_EXPENSES = " + json.dumps(expenses, indent=2, ensure_ascii=False) + ";\n"
    )
    with open(out_path, "w", encoding="utf-8") as f:
        f.write(header + body)

    print(f"Wrote {out_path}")
    print(f"  sales={len(sales)} expenses={len(expenses)}")
    print(f"  revenue=£{rev:,.2f} landing=£{landing:,.2f} "
          f"expenses=£{exp_total:,.2f} filament=£{filament:,.2f}")


if __name__ == "__main__":
    main()
